wallpaper {
    monitor = DP-1
    path = ~/Wallpapers/wallhaven-1q1919.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Wallpapers/wallhaven-zpzlzw.png
    fit_mode = cover
}

